feat: enable gosec and default linter set
edgexfoundry/device-rest-go pull request #166
Opened 2022-03-30 22:19 UTC by jpwhitemn

addressed lint errors found in the code

Fixes #165

Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-rest-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)  No docs to change for build feature
  <link to docs PR>

## Testing Instructions

run make lint target in the Makefile

## New Dependency Instructions (If applicable)

2022-03-31 00:42 UTC, bnevis-i approved these changes

2022-03-31 02:55 UTC, bnevis-i commented
recheck

2022-03-31 03:42 UTC, bnevis-i commented
@cloudxxx8 Review requested.

2022-03-31 16:40 UTC, lenny-intel requested changes

2022-03-31 16:40 UTC, lenny-intel commented on driver/restdriver.go
> +	//asyncValues chan<- *dsModels.AsyncValues
Remove commented out code.

2022-03-31 16:40 UTC, lenny-intel commented on driver/resthandler.go
> +		if ok {
Should be:
```suggestion
		if !ok {
```
And for the other also.

2022-04-01 00:49 UTC, bnevis-i approved these changes

2022-04-05 20:05 UTC, lenny-intel approved these changes

2022-04-05 20:05 UTC, merged