refactor(snap): edgex-snap-hooks related upgrade
edgexfoundry/device-rest-go pull request #202
Opened 2022-06-29 07:18 UTC by MonicaisHer

Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-rest-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-06-30 12:58 UTC, MonicaisHer commented
@farshidtz Could you please review this? Thanks

2022-07-01 11:53 UTC, farshidtz requested changes

2022-07-01 11:53 UTC, farshidtz commented on snap/local/helper-go/configure.go
> +
`log.SetComponentName("configure")` should be added to the beginning of the function so that all calls to log function use that in the syslog tag.

2022-07-01 11:53 UTC, farshidtz commented on snap/local/helper-go/configure.go
> +		log.Fatalf("edgex-device-rest:configure: can't read value of 'debug': %v", err)
'debug' handling is done internally in the log package. It doesn't need to be repeated here.

https://github.com/canonical/edgex-snap-hooks/blob/cbda5ae2568b3acc8376c0194c2556c594e30a30/log/init.go#L20-L25

2022-07-01 11:53 UTC, farshidtz commented on snap/local/helper-go/configure.go
> +		log.Fatalf("edgex-device-rest:configure: initialization failure: %v", err)
The prefix would be redundant if component name is set in advance.

2022-07-07 10:14 UTC, farshidtz approved these changes
Thanks. Looks good.

I just added a commit to include the patch release of the hook dependency.

2022-07-07 10:30 UTC, merged